#!/bin/bash

set -x

if [ ! -d $OPENSHIFT_DATA_DIR/gradle-3.1 ]
then
    cd $OPENSHIFT_DATA_DIR
    mkdir gradle
    wget http://services.gradle.org/distributions/gradle-3.1-bin.zip
    unzip gradle-3.1-bin.zip
    rm -f gradle-3.1-bin.zip
fi
